name: Setup Rust
description: 'Ensure Rust compiler and utilities are available, and setup caching'

inputs:
  kind:
    type: choice
    description: "Whether to install just a default target, or all targets (e.g. for during deployments / wheel building)"
    default: "full"
    options:
        - full
        - wasm

runs:
  using: 'composite'
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # latest
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Configure Cargo cache paths
      run: |
        if [ -z "${CARGO_TARGET_DIR:-}" ]; then
          echo "CARGO_TARGET_DIR=${GITHUB_WORKSPACE}/target" >> "${GITHUB_ENV}"
        fi
        echo "CARGO_TERM_COLOR=always" >> "${GITHUB_ENV}"
      shell: bash

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        key: ${{ runner.os }}-${{ inputs.kind }}
        cache-targets: true
        cache-all-crates: true
        cache-bin: true
        cache-on-failure: true
        cache-directories: |
          .cargo
          .rustup

    - run: |
        rustup target add aarch64-unknown-linux-gnu
        rustup target add x86_64-unknown-linux-gnu
      shell: bash
      if: ${{ inputs.kind == 'full' && runner.os == 'Linux' }}

    - run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
      shell: bash
      if: ${{ inputs.kind == 'full' && runner.os == 'macOS' }}

    - run: |
        rustup target add x86_64-pc-windows-msvc
        rustup target add aarch64-pc-windows-msvc
      shell: bash
      if: ${{ inputs.kind == 'full' && runner.os == 'Windows' }}

    - run: rustup target add wasm32-unknown-unknown
      shell: bash
      if: ${{ inputs.kind == 'wasm' }}
